export const ALL_PATIENTS_REQUEST = 'ALL_PATIENTS_REQUEST';
export const ALL_PATIENTS_SUCCESS = 'ALL_PATIENTS_SUCCESS';
export const ALL_PATIENTS_FAIL = 'ALL_PATIENTS_FAIL';

export const ALL_DOCTORS_REQUEST = 'ALL_DOCTORS_REQUEST';
export const ALL_DOCTORS_SUCCESS = 'ALL_DOCTORS_SUCCESS';
export const ALL_DOCTORS_FAIL = 'ALL_DOCTORS_FAIL';

export const ADD_DOCTOR_REQUEST = 'ADD_DOOTOR_REQUEST';
export const ADD_DOCTOR_SUCCESS = 'ADD_DOOTOR_SUCCESS';
export const ADD_DOCTOR_FAIL = 'ADD_DOOTOR_FAIL';
export const ADD_DOCTOR_RESET = 'ADD_DOCTOR_RESET';

export const UPDATE_DOCTOR_REQUEST = 'UPDATE_DOCTOR_REQUEST';
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS';
export const UPDATE_DOCTOR_RESET = 'UPDATE_DOCTOR_RESET';
export const UPDATE_DOCTOR_FAIL = 'UPDATE_DOCTOR_FAIL';

export const DOCTOR_PROFILE_REQUEST = 'DOCTOR_PROFILE_REQUEST';
export const DOCTOR_PROFILE_SUCCESS = 'DOCTOR_PROFILE_SUCCESS'; 
export const DOCTOR_PROFILE_FAIL = 'DOCTOR_PROFILE_FAIl';

export const PATIENT_PROFILE_REQUEST = 'PATIENT_PROFILE_REQUEST';
export const PATIENT_PROFILE_SUCCESS = 'PATIENT_PROFILE_SUCCESS'; 
export const PATIENT_PROFILE_FAIL = 'PATIENT_PROFILE_FAIl';

export const ASSIGN_PATIENT_TO_DOCTOR_REQUEST = 'ASSIGN_PATIENT_TO_DOCTOR_REQUEST';
export const ASSIGN_PATIENT_TO_DOCTOR_SUCCESS = 'ASSIGN_PATIENT_TO_DOCTOR_SUCCESS';
export const ASSIGN_PATIENT_TO_DOCTOR_FAIL = 'ASSIGN_PATIENT_TO_DOCTOR_FAIL';

export const ASSIGN_DEVICE_TO_PATIENT_REQUEST = 'ASSIGN_DEVICE_TO_PATIENT_REQUEST';
export const ASSIGN_DEVICE_TO_PATIENT_SUCCESS = 'ASSIGN_DEVICE_TO_PATIENT_SUCCESS';
export const ASSIGN_DEVICE_TO_PATIENT_FAIL = 'ASSIGN_DEVICE_TO_PATIENT_FAIL';

export const GET_PATIENT_DEVICE_DATA_REQUEST = 'GET_PATIENT_DEVICE_DATA_REQUEST';
export const GET_PATIENT_DEVICE_DATA_SUCCESS = 'GET_PATIENT_DEVICE_DATA_SUCCESS';
export const GET_PATIENT_DEVICE_DATA_FAIL = 'GET_PATIENT_DEVICE_DATA_FAIL';

export const GET_DEVICES_LIST_REQUEST = 'GET_DEVICES_LIST_REQUEST';
export const GET_DEVICES_LIST_SUCCESS = 'GET_DEVICES_LIST_SUCCESS';
export const GET_DEVICES_LIST_FAIL = 'GET_DEVICES_LIST_FAIL';

export const GET_DEVICE_DETAILS_REQUEST = 'GET_DEVICE_DETAILS_REQUEST';
export const GET_DEVICE_DETAILS_SUCCESS = 'GET_DEVICE_DETAILS_SUCCESS';
export const GET_DEVICE_DETAILS_FAIL = 'GET_DEVICE_DETAILS_FAIL';

export const ADD_RPM_DEVICE_REQUEST = 'ADD_RPM_DEVICE_REQUEST';
export const ADD_RPM_DEVICE_SUCCESS = 'ADD_RPM_DEVICE_SUCCESS';
export const ADD_RPM_DEVICE_FAIL = 'ADD_RPM_DEVICE_FAIL';
export const ADD_RPM_DEVICE_RESET = 'ADD_RPM_DEVICE_RESET';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';
