export const ALL_PATIENTS_REQUEST = 'ALL_PATIENTS_REQUEST';
export const ALL_PATIENTS_SUCCESS = 'ALL_PATIENTS_SUCCESS';
export const ALL_PATIENTS_FAIL = 'ALL_PATIENTS_FAIL';

export const ALL_DOCTORS_REQUEST = 'ALL_DOCTORS_REQUEST';
export const ALL_DOCTORS_SUCCESS = 'ALL_DOCTORS_SUCCESS';
export const ALL_DOCTORS_FAIL = 'ALL_DOCTORS_FAIL';

export const ADD_DOCTOR_REQUEST = 'ADD_DOOTOR_REQUEST';
export const ADD_DOCTOR_SUCCESS = 'ADD_DOOTOR_SUCCESS';
export const ADD_DOCTOR_FAIL = 'ADD_DOOTOR_FAIL';
export const ADD_DOCTOR_RESET = 'ADD_DOCTOR_RESET';

export const UPDATE_DOCTOR_REQUEST = 'UPDATE_DOCTOR_REQUEST';
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS';
export const UPDATE_DOCTOR_RESET = 'UPDATE_DOCTOR_RESET';
export const UPDATE_DOCTOR_FAIL = 'UPDATE_DOCTOR_FAIL';

export const DOCTOR_PROFILE_REQUEST = 'DOCTOR_PROFILE_REQUEST';
export const DOCTOR_PROFILE_SUCCESS = 'DOCTOR_PROFILE_SUCCESS'; 
export const DOCTOR_PROFILE_FAIL = 'DOCTOR_PROFILE_FAIl';

export const DOCTOR_PATIENTS_REQUEST = 'DOCTOR_PATIENTS_REQUEST';
export const DOCTOR_PATIENTS_SUCCESS = 'DOCTOR_PATIENTS_SUCCESS'; 
export const DOCTOR_PATIENTS_FAIL = 'DOCTOR_PATIENTS_FAIL';

export const PATIENT_PROFILE_REQUEST = 'PATIENT_PROFILE_REQUEST';
export const PATIENT_PROFILE_SUCCESS = 'PATIENT_PROFILE_SUCCESS'; 
export const PATIENT_PROFILE_FAIL = 'PATIENT_PROFILE_FAIl';

export const ASSIGN_PATIENT_TO_DOCTOR_REQUEST = 'ASSIGN_PATIENT_TO_DOCTOR_REQUEST';
export const ASSIGN_PATIENT_TO_DOCTOR_SUCCESS = 'ASSIGN_PATIENT_TO_DOCTOR_SUCCESS';
export const ASSIGN_PATIENT_TO_DOCTOR_FAIL = 'ASSIGN_PATIENT_TO_DOCTOR_FAIL';
export const RESET_ASSIGN_PATIENT_TO_HR = 'RESET_ASSIGN_PATIENT_TO_HR';

export const ASSIGN_DEVICE_TO_PATIENT_REQUEST = 'ASSIGN_DEVICE_TO_PATIENT_REQUEST';
export const ASSIGN_DEVICE_TO_PATIENT_SUCCESS = 'ASSIGN_DEVICE_TO_PATIENT_SUCCESS';
export const ASSIGN_DEVICE_TO_PATIENT_FAIL = 'ASSIGN_DEVICE_TO_PATIENT_FAIL';

export const GET_PATIENT_DEVICE_DATA_REQUEST = 'GET_PATIENT_DEVICE_DATA_REQUEST';
export const GET_PATIENT_DEVICE_DATA_SUCCESS = 'GET_PATIENT_DEVICE_DATA_SUCCESS';
export const GET_PATIENT_DEVICE_DATA_FAIL = 'GET_PATIENT_DEVICE_DATA_FAIL';

export const GET_DEVICES_LIST_REQUEST = 'GET_DEVICES_LIST_REQUEST';
export const GET_DEVICES_LIST_SUCCESS = 'GET_DEVICES_LIST_SUCCESS';
export const GET_DEVICES_LIST_FAIL = 'GET_DEVICES_LIST_FAIL';

export const GET_DEVICE_DETAILS_REQUEST = 'GET_DEVICE_DETAILS_REQUEST';
export const GET_DEVICE_DETAILS_SUCCESS = 'GET_DEVICE_DETAILS_SUCCESS';
export const GET_DEVICE_DETAILS_FAIL = 'GET_DEVICE_DETAILS_FAIL';

export const ADD_RPM_DEVICE_RESET = 'ADD_RPM_DEVICE_RESET';

export const UPDATE_DEVICE_REQUEST = 'UPDATE_DEVICE_REQUEST';
export const UPDATE_DEVICE_SUCCESS = 'UPDATE_DEVICE_SUCCESS';
export const UPDATE_DEVICE_RESET = 'UPDATE_DEVICE_RESET';
export const UPDATE_DEVICE_FAIL = 'UPDATE_DEVICE_FAIL';

export const SORT_DEVICES_REQUEST = 'SORT_DEVICES_REQUEST';
export const SORT_DEVICES_SUCCESS = 'SORT_DEVICES_SUCCESS';
export const SORT_DEVICES_FAIL = 'SORT_DEVICES_FAIL';

export const SORT_DEVICES_BY_BROKEN_REQUEST = 'SORT_DEVICES_BY_BROKEN_REQUEST';
export const SORT_DEVICES_BY_BROKEN_SUCCESS = 'SORT_DEVICES_BY_BROKEN_SUCCESS';
export const SORT_DEVICES_BY_BROKEN_FAIL = 'SORT_DEVICES_BY_BROKEN_FAIL';

export const DELETE_RPM_DEVICE_REQUEST = 'DELETE_RPM_DEVICE_REQUEST';
export const DELETE_RPM_DEVICE_SUCCESS = 'DELETE_RPM_DEVICE_SUCCESS';
export const DELETE_RPM_DEVICE_FAIL = 'DELETE_RPM_DEVICE_FAIL';
export const DELETE_RPM_DEVICE_RESET = 'DELETE_RPM_DEVICE_RESET';

export const ADD_PATIENT_REQUEST = 'ADD_PATIENT_REQUEST';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAIL = 'ADD_PATIENT_FAIL';
export const PATIENT_RESET = 'PATIENT_RESET';

export const UPDATE_PATIENT_REQUEST = 'UPDATE_PATIENT_REQUEST';
export const UPDATE_PATIENT_SUCCESS = 'UPDATE_PATIENT_SUCCESS';
export const UPDATE_PATIENT_FAIL = 'UPDATE_PATIENT_FAIL';
export const UPDATE_PATIENT_RESET = 'UPDATE_PATIENT_REQUEST';

export const ALL_HRS_REQUEST = 'ALL_HRS_REQUEST';
export const ALL_HRS_SUCCESS = 'ALL_HRS_SUCCESS';
export const ALL_HRS_FAIL = 'ALL_HRS_FAIL';

export const ADD_HR_REQUEST = 'ADD_HR_REQUEST';
export const ADD_HR_SUCCESS = 'ADD_HR_SUCCESS';
export const ADD_HR_FAIL = 'ADD_HR_FAIL';

export const UPDATE_HR_REQUEST = 'UPDATE_HR_REQUEST';
export const UPDATE_HR_SUCCESS = 'UPDATE_HR_SUCCESS';
export const UPDATE_HR_FAIL = 'UPDATE_HR_FAIL';
export const UPDATE_HR_RESET = 'UPDATE_HR_RESET';

export const ASSIGN_DOCTOR_TO_HR_REQUEST = 'ASSIGN_DOCTOR_TO_HR_REQUEST';
export const ASSIGN_DOCTOR_TO_HR_SUCCESS = 'ASSIGN_DOCTOR_TO_HR_SUCCESS';
export const ASSIGN_DOCTOR_TO_HR_FAIL = 'ASSIGN_DOCTOR_TO_HR_FAIL';

export const ADMIN_STATS_SUCCESS = 'ADMIN_STATS_SUCCESS';
export const ADMIN_STATS_FAIL = 'ADMIN_STATS_FAIL';

export const INVENTORY_STATS_SUCCESS = 'INVENTORY_STATS_SUCCESS';
export const INVENTORY_STATS_FAIL = 'INVENTORY_STATS_FAIL'

export const GET_ADMIN_NOTIFICATIONS_REQUEST = 'GET_ADMIN_NOTIFICATIONS_REQUEST';
export const GET_ADMIN_NOTIFICATIONS_SUCCESS = 'GET_ADMIN_NOTIFICATIONS_SUCCESS';
export const GET_ADMIN_NOTIFICATIONS_FAIL = 'GET_ADMIN_NOTIFICATIONS_FAIL';

export const GET_LOGS_REQUEST = "GET_LOGS_REQUEST";
export const GET_LOGS_SUCCESS = "GET_LOGS_SUCCESS";
export const GET_LOGS_FAIL = "GET_LOGS_FAIL"

export const GET_PATIENT_REMAINING_READINGS = 'GET_PATIENT_REMAINING_READINGS';

export const HR_PROFILE_SUCCESS = "HR_PROFILE_SUCCESS";
export const HR_PROFILE_FAIL = "HR_PROFILE_FAIL"

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
