
export const HR_PATIENTS_REQUEST = 'HR_PATIENTS_REQUEST';
export const HR_PATIENTS_SUCCESS = 'HR_PATIENTS_SUCCESS';
export const HR_PATIENTS_FAIL = 'HR_PATIENTS_FAIL';

export const ADDING_COMMENT_REQUEST = 'ADDING_COMMENT_REQUEST';
export const ADDING_COMMENT_SUCCESS = 'ADDING_COMMENT_SUCCESS';
export const ADDING_COMMENT_FAIL = 'ADDING_COMMENT_FAIL';
export const COMMENT_RESET = 'COMMENT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

