
export const HR_PATIENTS_REQUEST = 'HR_PATIENTS_REQUEST';
export const HR_PATIENTS_SUCCESS = 'HR_PATIENTS_SUCCESS';
export const HR_PATIENTS_FAIL = 'HR_PATIENTS_FAIL';

export const ADDING_COMMENT_REQUEST = 'ADDING_COMMENT_REQUEST';
export const ADDING_COMMENT_SUCCESS = 'ADDING_COMMENT_SUCCESS';
export const ADDING_COMMENT_FAIL = 'ADDING_COMMENT_FAIL';
export const COMMENT_RESET = 'COMMENT_RESET';

export const ADDING_TIME_SPENT_SUCCESS = 'ADDING_TIME_SPENT_SUCCESS';
export const ADDING_TIME_SPENT_FAIL = 'ADDING_TIME_SPENT_FAIL';
export const ADDING_TIME_SPENT_RESET = 'ADDING_TIME_SPENT_RESET';

export const TIME_REPORT_REQUEST = 'TIME_REPORT_REQUEST';
export const TIME_REPORT_SUCCESS = 'TIME_REPORT_SUCCESS';
export const TIME_REPORT_FAIL = 'TIME_REPORT_FAIL'
export const RESET_TIME_REPORT_DATA = 'RESET_TIME_REPORT_DATA';

export const INITIAL_MONTH_REPORT_REQUEST = 'INITIAL_MONTH_REPORT_REQUEST';
export const INITIAL_MONTH_REPORT_SUCCESS = 'INITIAL_MONTH_REPORT_SUCCESS';
export const INITIAL_MONTH_REPORT_FAIL ='INITIAL_MONTH_REPORT_FAIL'; 
export const RESET_INITIAL_MONTH_DATA = 'RESET_INITIAL_MONTH_DATA';

export const ADDING_CARE_PLAN_SUCCESS = 'ADDING_CARE_PLAN_SUCCESS';
export const ADDING_CARE_PLAN_RESET = 'ADDING_CARE_PLAN_RESET';
export const ADDING_CARE_PLAN_FAIL = 'ADDING_CARE_PLAN_FAIL'

export const PATIENT_CARE_PLAN_SUCCESS = 'PATIENT_CARE_PLAN_SUCCESS';
export const PATIENT_CARE_PLAN_FAIL = 'PATIENT_CARE_PLAN_FAIL';

export const UPDATE_CARE_PLAN_SUCCESS = 'UPDATE_CARE_PLAN_SUCCESS';
export const UPDATE_CARE_PLAN_FAIL = 'UPDATE_CARE_PLAN_FAIL';
export const UPDATE_CARE_PLAN_RESET = 'UPDATE_CARE_PLAN_RESET';

export const TIME_SPENT_OF_CURRENT_MONTH_SUCCESS = 'TIME_SPENT_OF_CURRENT_MONTH_SUCCESS';
export const TIME_SPENT_OF_CURRENT_MONTH_FAIL = 'TIME_SPENT_OF_CURRENT_MONTH_FAIL';

export const PATIENT_CP_REPORT_REQUEST = 'PATIENT_CP_REPORT_REQUEST';
export const PATIENT_CP_REPORT_SUCCESS = 'PATIENT_CP_REPORT_SUCCESS';
export const PATIENT_CP_REPORT_FAIL = 'PATIENT_CP_REPORT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

