import React from 'react';
import logo from '../assets/Images/tdw_logo.jpeg'
import systolicImg from '../assets/Images/blood-pressure.png';
import diastolicImg from '../assets/Images/diastolic.png';
import pulseImg from '../assets/Images/pulse.png';
import weightImg from '../assets/Images/scale.png';
import fatImg from '../assets/Images/fat.png';
import bmiImg from '../assets/Images/bmi.png';

import moment from 'moment';

export default class MyDocument extends React.PureComponent {
    render() {
         const { healthData } = this.props;

      return (
          <div>
          {healthData && healthData.map((data, index) => (
            <div key={index}>
            <div className="container row-display">
                <img src={logo} width="170" height="110" alt="logo" />

                <div>
                    <p className="mt-4"><b>Date Printed: </b>  {moment().tz("America/New_York").format("lll")} </p>
                    <i>Generated By Admin</i> 
                </div>
            </div>

            <hr />

            <h4 className="text-center"><b>Telemetary Data Report</b></h4>
            <br />
            <div style={{marginLeft: '60px', marginRight: '60px'}}>

            <div className="row-display">
                <div className="row-display" style={{width: '35%'}}>
                    <div>
                        <b>Patient Name: </b>
                    </div>
                    <div>
                        Pt. {data?.assigned_patient_id?.firstname}  {data?.assigned_patient_id?.lastname}
                    </div>
                </div>

                <div className="row-display" style={{width: '25%'}}>
                    <div>
                        <b>Device ID: </b>
                    </div>
                <div>
                    {data?.deviceId?._id || 'N/A'}
                </div> 
              </div>
            </div>

            <br/>

            <div className="row-display">
                <div className="row-display" style={{width: '30%',  float: 'left'}}>
                    <div>
                        <b>Patient Gender: </b>
                    </div>
                    <div>
                        {data?.assigned_patient_id?.gender} 
                    </div>
                </div>

                <div className="row-display" style={{width: '25%', float: 'left'}}>
                    <div>
                        <b>Device IMEI: </b>
                    </div>
                <div>
                    {data?.deviceId?.imei || 'N/A'}
                </div> 
              </div>
            </div>

            <br />
                <div style={{display: 'flex', flexDirection: 'column', width: "25%", float:'right'}}>
                    <div className="row-display">
                        <b>Model #: </b> {data?.deviceId?.modelNumber || 'N/A'} 
                    </div>
    
                    <br />
                    <div className="row-display">
                            <b>Device Type: </b> {data?.deviceId?.deviceType || 'N/A'} 
                    </div>
                </div>

                <h5 className="text-center" style={{color: '#ed1b24', marginTop: '120px'}}><b>Telemetary Result</b></h5>
            <br />

            <div className="row-display">
                <div className="row-display">
                    <img src={data?.telemetaryData?.sys ? systolicImg : fatImg} alt="" className="systolic-image" />


                    <b style={{marginLeft: "20px", marginTop: '10px'}}>{data?.telemetaryData?.sys ? "Systolic" : "Fat"} : {data?.telemetaryData?.sys ? data?.telemetaryData?.sys : data?.telemetaryData?.fat}</b> 
                    <b style={{marginLeft: "20px", marginTop: '10px'}}> ( Normal )</b>
                </div>

                <div className="row-display">
                    <img src={data?.telemetaryData?.dia ? diastolicImg : weightImg} alt="" className="systolic-image" />

                    <b style={{marginLeft: "20px", marginTop: '10px'}}>{data?.telemetaryData?.dia ? "Diastolic" : "Weight"} : {data?.telemetaryData?.dia ? data?.telemetaryData?.dia : (data?.telemetaryData?.wt / 454).toFixed() + "lbs" }</b>  
                    <b style={{marginLeft: "20px", marginTop: '10px'}}> ( Normal ) </b>
                </div>

                <div className="row-display">
                    <img src={data?.telemetaryData?.pul ? pulseImg : bmiImg} alt="" className="systolic-image" />

                    <b style={{marginLeft: "20px", marginTop: '10px'}}>{data?.telemetaryData?.pul ? "Pulse" : "BMI"} : {data?.telemetaryData?.pul ? data?.telemetaryData?.pul : data?.telemetaryData?.bmi}</b>  

                    <b style={{marginLeft: "20px", marginTop: '10px'}}> ( Normal ) </b>
                </div>
            </div>

            <div style={{marginTop: "880px"}}>
                <small><b>This document is computer generated and does not require the doctor's signature or the Company's stamp in order to be considered valid.</b></small>
            </div>
            <br />

            <hr />
            <div style={{float: "right"}}>
                <small><b>Record {index + 1} of {healthData?.length}</b></small>
            </div>
            </div>            
            </div>
          ))}
        </div>
      );
    }
  }